name: Run league

on:
  workflow_dispatch:
    inputs:
      league:
        description: "Nome da liga (ex.: Ligue 1, La Liga, Bundesliga, MLS, Brasileirão, etc.)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingestor
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python -u src/ingestor.py --league "${{ inputs.league }}"
