name: run-ligue1

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      LEAGUE: "Ligue 1"
      FROM_SCRATCH: "true"
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingestor (Ligue 1, from scratch = true)
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          SPREADSHEET_ID: ${{ env.SPREADSHEET_ID }}
        run: |
          MODE=$([ "${FROM_SCRATCH}" = "true" ] && echo "from-scratch" || echo "update")
          python src/ingestor.py --league "${LEAGUE}" --mode "${MODE}"
