name: run-ligue1

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      # <<< FIXOS, COMO VOCÊ PEDIU >>>
      LEAGUE: "Ligue 1"
      FROM_SCRATCH: "true"
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service-account key
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > sa.json

      - name: Run ingestor (Ligue 1, from scratch = true)
        run: |
          python src/ingestor.py
