name: run-league

on:
  workflow_dispatch:
    inputs:
      league:
        description: Nome da liga (igual à aba do Sheets)
        required: true
        default: "Ligue 1"
      from_scratch:
        description: Resetar a aba antes de preencher (true/false)
        required: true
        default: "true"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service-account key
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > sa.json

      - name: Run ingestor
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          LEAGUE: ${{ github.event.inputs.league }}
          FROM_SCRATCH: ${{ github.event.inputs.from_scratch }}
        run: |
          python src/ingestor.py
